let state={businessName:"Your Business",businessPhone:"",businessLogo:"",paymentProvider:"Manual bank transfer",paymentLink:"",paymentDetails:"",plan:"starter",products:[],customers:[],orders:[],events:[]};
let pricing={};
let authToken=null;
const $=id=>document.getElementById(id), money=n=>`NGN ${Number(n||0).toLocaleString("en-NG")}`;
const clean=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
const toast=m=>{const t=$("toast");t.textContent=m;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2000)};
async function api(method,url,body){const res=await fetch(url,{method,headers:{...(body?{"Content-Type":"application/json"}:{}),Authorization:`Bearer ${authToken}`},body:body?JSON.stringify(body):undefined});if(!res.ok){const err=await res.json().catch(()=>({error:"Request failed"}));throw new Error(err.error||"Request failed")}return res.status===204?null:res.json()}
function applyState(s){Object.assign(state,s.business,{products:s.products,customers:s.customers,orders:s.orders,events:s.events})}
async function loadState(){const [s,p]=await Promise.all([api("GET","/api/state"),api("GET","/api/pricing")]);applyState(s);pricing=p}
const orderLimit=()=>{const raw=pricing[state.plan]?.orderLimit;return raw===undefined?20:raw===null?Infinity:raw};
const product=id=>state.products.find(x=>x.id===id), customer=id=>state.customers.find(x=>x.id===id), total=o=>(product(o.productId)?.price||o.price||0)*o.qty;
const date=d=>new Intl.DateTimeFormat("en-NG",{month:"short",day:"numeric",year:"numeric"}).format(new Date(d));
document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>show(b.dataset.tab));
function show(tab){document.querySelectorAll(".tab").forEach(b=>b.classList.toggle("active",b.dataset.tab===tab));document.querySelectorAll(".page").forEach(p=>p.classList.toggle("active",p.id===tab));$("title").textContent={dash:"Dashboard",products:"Products",customers:"Customers",orders:"Orders",invoice:"Invoice",ai:"AI Tools",settings:"Settings"}[tab]}
function opts(el,items,label,empty){el.innerHTML="";if(!items.length){el.innerHTML=`<option value="">${empty}</option>`;return}items.forEach(x=>el.add(new Option(label(x),x.id)))}
function bestProduct(){const t={};state.orders.forEach(o=>{const n=product(o.productId)?.name||o.productName;if(n)t[n]=(t[n]||0)+o.qty});return Object.entries(t).sort((a,b)=>b[1]-a[1])[0]?.[0]}
function render(){
  $("pList").innerHTML=state.products.map(p=>`<div class="item"><div class="item-top"><strong>${clean(p.name)}</strong><span>${money(p.price)}</span></div><div class="meta">${clean(p.type||"Product")} - ${clean(p.category||"General")} - ${p.stock} ${p.type==="Service"?"slots":p.type==="Digital product"?"licenses":"in stock"}</div><div class="item-actions"><button onclick="caption('${p.id}')">Caption</button><button onclick="delProduct('${p.id}')">Delete</button></div></div>`).join("");
  $("cList").innerHTML=state.customers.map(c=>`<div class="item"><div class="item-top"><strong>${clean(c.name)}</strong><span>${clean(c.location||"No location")}</span></div><div class="meta">${clean(c.phone)}</div><div class="item-actions"><button onclick="wa('Hello, thank you for shopping with us. How can we help you today?','${c.phone}')">Message</button><button onclick="delCustomer('${c.id}')">Delete</button></div></div>`).join("");
  $("oList").innerHTML=state.orders.map(o=>{const p=product(o.productId),c=customer(o.customerId);return `<div class="item"><div class="item-top"><strong>${clean(c?.name||"Deleted customer")}</strong><span>${money(total(o))}</span></div><div class="meta">${clean(p?.name||o.productName)} x ${o.qty} - ${clean(o.status)} - ${date(o.createdAt)}</div><div class="item-actions"><button onclick="openInvoice('${o.id}')">Invoice</button><button onclick="wa(orderMsg('${o.id}'),'${c?.phone||""}')">WhatsApp</button><button onclick="paid('${o.id}')">Paid</button>${(p?.type||o.productType)==="Digital product"?`<button onclick="deliverDigital('${o.id}')">Deliver</button>`:""}<button onclick="delOrder('${o.id}')">Delete</button></div></div>`}).join("");
  $("pCount").textContent=`${state.products.length} items`;$("cCount").textContent=`${state.customers.length} people`;$("oCount").textContent=`${state.orders.length} orders`;$("used").textContent=state.orders.length;
  if($("planName"))$("planName").textContent=pricing[state.plan]?.name||state.plan;
  if($("orderLimit")){const lim=orderLimit();$("orderLimit").textContent=lim===Infinity?"unlimited":lim}
  const priceLabel=t=>t.monthly===0?"Free":t.monthly==null?"Custom Pricing":money(t.monthly)+"/month";
  if($("pricingPlans"))$("pricingPlans").innerHTML=Object.entries(pricing).map(([key,t])=>`<div class="${key===state.plan?"featured":""}"><b>${clean(t.name)}</b><span>${priceLabel(t)}</span><small>${clean(t.tagline)}</small></div>`).join("");
  if($("paywallPlans"))$("paywallPlans").innerHTML=Object.entries(pricing).filter(([key,t])=>key!=="starter"&&t.monthly!=null).map(([key,t],i)=>`<div class="${i===0?"featured":""}"><b>${clean(t.name)}</b><span>${priceLabel(t)}</span><small>${clean(t.tagline)}</small></div>`).join("");
  const rev=state.orders.filter(o=>["Paid","Delivered"].includes(o.status)).reduce((s,o)=>s+total(o),0), low=state.products.filter(p=>p.stock<5), pending=state.orders.filter(o=>o.status==="Pending payment").length;
  $("rev").textContent=money(rev);$("ordMetric").textContent=state.orders.length;$("custMetric").textContent=state.customers.length;$("lowMetric").textContent=low.length;
  $("summary").innerHTML=`<b>${state.orders.length}</b> orders recorded.<br><b>${pending}</b> orders need payment follow-up.<br>Best seller: <b>${clean(bestProduct()||"Not enough sales yet")}</b>.<br>Paid revenue: <b>${money(rev)}</b>.`;
  $("restock").innerHTML=low.map(p=>`<div class="item"><strong>${clean(p.name)}</strong><span class="meta">${p.stock} left - restock soon</span></div>`).join("");
  opts($("oCustomer"),state.customers,c=>c.name,"Add a customer first");opts($("oProduct"),state.products,p=>`${p.name} - ${money(p.price)} - ${p.stock} left`,"Add a product first");opts($("aiProduct"),state.products,p=>p.name,"Add a product first");opts($("aiCustomer"),state.customers,c=>c.name,"Add a customer first");opts($("invSelect"),state.orders,o=>`${customer(o.customerId)?.name||"Customer"} - ${money(total(o))}`,"No orders yet");renderInvoice();
}
$("productForm").onsubmit=async e=>{e.preventDefault();const created=await api("POST","/api/products",{name:$("pName").value.trim(),price:+$("pPrice").value,stock:+$("pStock").value,category:$("pCat").value.trim(),type:$("pType")?.value||"Product",deliveryLink:$("pDelivery")?.value.trim()||"",deliveryNote:$("pNote")?.value.trim()||""});state.products.unshift(created);e.target.reset();render();toast("Item saved")};
$("customerForm").onsubmit=async e=>{e.preventDefault();const created=await api("POST","/api/customers",{name:$("cName").value.trim(),phone:$("cPhone").value.replace(/\D/g,""),location:$("cLoc").value.trim()});state.customers.unshift(created);e.target.reset();render();toast("Customer saved")};
$("orderForm").onsubmit=async e=>{e.preventDefault();const p=product($("oProduct").value),c=customer($("oCustomer").value),q=+$("oQty").value;if(state.orders.length>=orderLimit()){showPaywall();return}if(!p||!c)return toast("Add product and customer first");if(q>p.stock)return toast("Not enough stock");try{const created=await api("POST","/api/orders",{productId:p.id,customerId:c.id,qty:q,status:$("oStatus").value});p.stock-=q;state.orders.unshift(created);e.target.reset();$("oQty").value=1;render();toast("Order created")}catch(err){toast(err.message)}};
function renderInvoice(){const o=state.orders.find(x=>x.id===$("invSelect").value)||state.orders[0];if(!o){$("invoiceBox").textContent="Create an order first.";return}$("invSelect").value=o.id;const c=customer(o.customerId),p=product(o.productId);$("invoiceBox").innerHTML=`${state.businessLogo?`<img class="invoice-logo" src="${state.businessLogo}" alt="Business logo">`:""}<h2>${["Paid","Delivered"].includes(o.status)?"Receipt":"Invoice"}</h2><div class="row"><span>Business</span><b>${clean(state.businessName)}</b></div><div class="row"><span>Business phone</span><b>${clean(state.businessPhone||"")}</b></div><div class="row"><span>Date</span><b>${date(o.createdAt)}</b></div><div class="row"><span>Customer</span><b>${clean(c?.name||"")}</b></div><div class="row"><span>Phone</span><b>${clean(c?.phone||"")}</b></div><div class="row"><span>Product</span><b>${clean(p?.name||o.productName)}</b></div><div class="row"><span>Quantity</span><b>${o.qty}</b></div><div class="row"><span>Status</span><b>${clean(o.status)}</b></div><div class="row"><span>Total</span><b>${money(total(o))}</b></div>${digitalDeliveryHtml(o,p)}<div class="row"><span>Payment provider</span><b>${clean(state.paymentProvider||"Manual bank transfer")}</b></div><div class="row"><span>Payment</span><b>${clean(state.paymentDetails||"Add payment details in Settings")}</b></div>${state.paymentLink?`<a class="payment-link" href="${state.paymentLink}" target="_blank" rel="noopener">Pay online</a>`:""}`}
function invoiceText(){const o=state.orders.find(x=>x.id===$("invSelect").value)||state.orders[0];if(!o)return "";const c=customer(o.customerId),p=product(o.productId);return `${["Paid","Delivered"].includes(o.status)?"Receipt":"Invoice"} from ${state.businessName}\nDate: ${date(o.createdAt)}\nCustomer: ${c?.name||""}\nProduct: ${p?.name||o.productName}\nQuantity: ${o.qty}\nStatus: ${o.status}\nTotal: ${money(total(o))}\nThank you for your order.`}
function orderMsg(id){const o=state.orders.find(x=>x.id===id),p=product(o.productId);return `Hello, your order for ${p?.name||o.productName} x ${o.qty} is ${o.status}. Total: ${money(total(o))}. Thank you.`}
function wa(msg,phone=""){open(`https://wa.me/${phone}?text=${encodeURIComponent(msg)}`,"_blank","noopener")}function copy(t){navigator.clipboard.writeText(t);toast("Copied")}
function openInvoice(id){show("invoice");$("invSelect").value=id;renderInvoice()}
async function paid(id){const updated=await api("PATCH",`/api/orders/${id}`,{markPaid:true});const idx=state.orders.findIndex(x=>x.id===id);if(idx>-1)state.orders[idx]=updated;render();toast("Marked paid");showReceipt(id)}
async function delProduct(id){await api("DELETE",`/api/products/${id}`);state.products=state.products.filter(x=>x.id!==id);render()}
async function delCustomer(id){await api("DELETE",`/api/customers/${id}`);state.customers=state.customers.filter(x=>x.id!==id);render()}
async function delOrder(id){await api("DELETE",`/api/orders/${id}`);state.orders=state.orders.filter(x=>x.id!==id);render()}
function caption(id){show("ai");$("aiTool").value="caption";$("aiProduct").value=id;generateAI()}
function generateAI(){const p=product($("aiProduct").value),c=customer($("aiCustomer").value),d=$("aiDetail").value.trim(),rev=state.orders.reduce((s,o)=>s+total(o),0);const out={caption:`New arrival: ${p?.name||"our product"}.\n\nClean quality, fair price, and ready for fast delivery. Price: ${money(p?.price||0)}.\n\nSend a message now to order before stock runs out.`,reply:`Hello ${c?.name||"there"}, thanks for reaching out.\n\n${d||"Yes, this item is available."}\n\nI can reserve it for you now and send your invoice immediately.`,reminder:`Hello ${c?.name||"there"}, this is a friendly reminder about your pending order.\n\nPlease complete payment so we can process delivery. Thank you for choosing us.`,summary:`Sales summary:\n\nTotal orders: ${state.orders.length}\nTotal recorded revenue: ${money(rev)}\nBest-selling item: ${bestProduct()||"Not enough sales yet"}\nPending payments: ${state.orders.filter(o=>o.status==="Pending payment").length}\n\nSuggested action: follow up pending payments and restock fast-moving products.`};$("aiOut").value=out[$("aiTool").value];toast("Message generated")}
$("invSelect").onchange=renderInvoice;$("copyInvoice").onclick=()=>copy(invoiceText());$("waInvoice").onclick=()=>{const o=state.orders.find(x=>x.id===$("invSelect").value)||state.orders[0];wa(invoiceText(),customer(o?.customerId)?.phone||"")};$("genAI").onclick=generateAI;$("copyAI").onclick=()=>copy($("aiOut").value);$("upgrade").onclick=()=>open("upgrade.html","_blank","noopener");$("export").onclick=()=>{const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:"application/json"}));a.download="sellpilot-data.json";a.click()};$("reset").onclick=async()=>{if(confirm("Reset all data?")){applyState(await api("POST","/api/reset"));render()}};$("demo").onclick=async()=>{applyState(await api("POST","/api/demo"));render();toast("Demo loaded")};

function showPaywall(){const d=$("paywall");if(d?.showModal)d.showModal();else toast("Upgrade to continue taking orders")}
function salesPitch(){const paid=Object.values(pricing).find(t=>t.monthly>0);return "Hi, SellersPoint Beta helps sellers and service businesses manage products, services, customers, orders, invoices, stock or slots, payment links, WhatsApp messages, and AI captions in one simple app."+(paid?` ${paid.name} plan is ${money(paid.monthly)}/month.`:"")}
if($("settingsForm")){$("settingsForm").onsubmit=async e=>{e.preventDefault();const updated=await api("PUT","/api/business",{businessName:$("sBusiness").value.trim(),businessPhone:$("sPhone").value.replace(/\D/g,""),paymentProvider:$("sProvider")?.value||"Manual bank transfer",paymentLink:$("sPaymentLink")?.value.trim()||"",paymentDetails:$("sPayment").value.trim()});Object.assign(state,updated);render();toast("Settings saved")}}
if($("closePaywall"))$("closePaywall").onclick=()=>$("paywall").close();
if($("copyPitch"))$("copyPitch").onclick=()=>copy(salesPitch());
if($("upgrade2"))$("upgrade2").onclick=()=>open("upgrade.html","_blank","noopener");
const oldRender=render;render=function(){oldRender();if($("sBusiness")){$("sBusiness").value=state.businessName||"";$("sPhone").value=state.businessPhone||"";$("sPayment").value=state.paymentDetails||"";if($("sProvider"))$("sProvider").value=state.paymentProvider||"Manual bank transfer";if($("sPaymentLink"))$("sPaymentLink").value=state.paymentLink||"";if($("brandLogo"))$("brandLogo").innerHTML=state.businessLogo?`<img src="${state.businessLogo}" alt="Logo">`:"SP"}};

if($("sLogo"))$("sLogo").onchange=e=>{const file=e.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=async()=>{const updated=await api("PUT","/api/business",{businessLogo:reader.result});Object.assign(state,updated);render();toast("Logo saved")};reader.readAsDataURL(file)};

function digitalDeliveryHtml(o,p){if((p?.type||o.productType)!=="Digital product")return "";if(!["Paid","Delivered"].includes(o.status)&&!o.delivered)return '<div class="delivery-box"><b>Digital delivery locked</b><br><span class="meta">Mark order as paid to reveal download/access details.</span></div>';let link=p?.deliveryLink?'<a href="'+p.deliveryLink+'" target="_blank" rel="noopener">Open download / access link</a><br>':'';return '<div class="delivery-box"><b>Digital delivery</b><br>'+link+'<span>'+clean(p?.deliveryNote||'No delivery note added.')+'</span></div>'}
function digitalDeliveryText(o,p){if((p?.type||o.productType)!=="Digital product")return "";if(!["Paid","Delivered"].includes(o.status)&&!o.delivered)return "\nDigital delivery: Access details will be sent after payment.";return "\nDigital delivery link: "+(p?.deliveryLink||"No link added")+"\nDelivery note: "+(p?.deliveryNote||"No delivery note added")}
async function deliverDigital(id){const updated=await api("PATCH",`/api/orders/${id}`,{deliver:true});const idx=state.orders.findIndex(x=>x.id===id);if(idx>-1)state.orders[idx]=updated;render();toast("Digital product delivered")}
function setupScore(){const checks=[state.businessName&&state.businessName!=="Your Business",state.businessPhone,state.paymentDetails||state.paymentLink,state.products.length,state.customers.length,state.orders.length,state.businessLogo];return Math.round(checks.filter(Boolean).length/checks.length*100)}
function renderBackend(){if(!$("devEvents"))return;const digitalRevenue=state.orders.filter(o=>(product(o.productId)?.type||o.productType)==="Digital product"&&["Paid","Delivered"].includes(o.status)).reduce((s,o)=>s+total(o),0);const storage=Math.round((JSON.stringify(state).length/1024)*10)/10;$("devEvents").textContent=state.events.length;$("devDigitalRevenue").textContent=money(digitalRevenue);$("devSetup").textContent=setupScore()+"%";$("devStorage").textContent=storage+" KB";const checks=[["Business profile",state.businessName&&state.businessName!=="Your Business"],["Logo uploaded",state.businessLogo],["Payment configured",state.paymentDetails||state.paymentLink],["First item added",state.products.length],["First customer added",state.customers.length],["First order created",state.orders.length],["Digital delivery ready",state.products.some(p=>p.type==="Digital product"&&p.deliveryLink)]];$("checklist").innerHTML=checks.map(x=>"<div class=\"check "+(x[1]?"done":"")+"\"><b>"+(x[1]?"✓":"!")+"</b><span>"+x[0]+"</span></div>").join("");const top=bestProduct()||"No sales yet";$("devSummary").innerHTML="<div class=\"item\"><strong>Top item</strong><span class=\"meta\">"+clean(top)+"</span></div><div class=\"item\"><strong>Orders</strong><span class=\"meta\">"+state.orders.length+" total, "+state.orders.filter(o=>o.status==="Pending payment").length+" pending payment</span></div><div class=\"item\"><strong>Catalog</strong><span class=\"meta\">"+state.products.filter(p=>p.type==="Product").length+" products, "+state.products.filter(p=>p.type==="Service").length+" services, "+state.products.filter(p=>p.type==="Digital product").length+" digital products</span></div>";$("eventLog").innerHTML=state.events.slice(0,12).map(e=>"<div class=\"item\"><strong><span class=\"badge\">"+clean(e.type)+"</span> "+clean(e.detail||"")+"</strong><span class=\"meta\">"+date(e.at)+"</span></div>").join("")}
function backendReport(){return "SellersPoint Beta report\nOrders: "+state.orders.length+"\nCustomers: "+state.customers.length+"\nItems: "+state.products.length+"\nSetup: "+setupScore()+"%\nTop item: "+(bestProduct()||"No sales yet")}
if($("copyReport"))$("copyReport").onclick=()=>copy(backendReport());if($("exportAnalytics"))$("exportAnalytics").onclick=()=>{const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify({generatedAt:new Date().toISOString(),summary:backendReport(),state},null,2)],{type:"application/json"}));a.download="sellerspoint-analytics.json";a.click()};
const renderForBackend=render;render=function(){renderForBackend();renderBackend()};

if($("openUpgrade"))$("openUpgrade").onclick=()=>open("upgrade.html","_blank","noopener");
function receiptText(o){if(!o)return "";const c=customer(o.customerId),p=product(o.productId);return "Receipt from "+state.businessName+"\nDate: "+date(new Date().toISOString())+"\nCustomer: "+(c?.name||"")+"\nItem: "+(p?.name||o.productName)+"\nQuantity: "+o.qty+"\nAmount paid: "+money(total(o))+"\nPayment status: Paid"+digitalDeliveryText(o,p)+"\nThank you for your payment."}
function showReceipt(id){const o=state.orders.find(x=>x.id===id);if(!o)return;const c=customer(o.customerId),p=product(o.productId);if($("receiptBox"))$("receiptBox").innerHTML=(state.businessLogo?"<img class=\"invoice-logo\" src=\""+state.businessLogo+"\" alt=\"Business logo\">":"")+"<h2>Receipt</h2><div class=\"row\"><span>Business</span><b>"+clean(state.businessName)+"</b></div><div class=\"row\"><span>Customer</span><b>"+clean(c?.name||"")+"</b></div><div class=\"row\"><span>Item</span><b>"+clean(p?.name||o.productName)+"</b></div><div class=\"row\"><span>Quantity</span><b>"+o.qty+"</b></div><div class=\"row\"><span>Amount paid</span><b>"+money(total(o))+"</b></div><div class=\"row\"><span>Status</span><b>Paid</b></div>"+digitalDeliveryHtml(o,p);window.currentReceiptOrderId=id;if($("receiptModal")?.showModal)$("receiptModal").showModal()}
if($("closeReceipt"))$("closeReceipt").onclick=()=>$("receiptModal").close();
if($("copyReceipt"))$("copyReceipt").onclick=()=>copy(receiptText(state.orders.find(x=>x.id===window.currentReceiptOrderId)));
if($("waReceipt"))$("waReceipt").onclick=()=>{const o=state.orders.find(x=>x.id===window.currentReceiptOrderId);wa(receiptText(o),customer(o?.customerId)?.phone||"")}

if($("logout"))$("logout").onclick=()=>window.Auth.logout();

(async()=>{const ctx=await window.Auth.requireSession();if(!ctx)return;authToken=ctx.session.access_token;loadState().then(render)})().catch(err=>toast(err.message||"Something went wrong loading this page."));
